language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Command to install dependencies.
install:
  - pip install -r requirements.txt
# Command to run tests.
script:
  - python rake_test.py
